name: 'Build and Publish Python Package'
description: 'Builds and publishes Python package to specified PyPI repository'

inputs:
  pypi-upload-url:
    description: 'Upload repository URL'
    required: true
    default: 'https://upload.pypi.org/legacy/'
  pypi-install-url:
    description: 'Install repository URL'
    required: true
    default: 'https://pypi.org/simple/'
  version-override:
    description: 'Override version (for dev builds)'
    required: false
    default: ''
  pypi-token:
    description: 'PyPI API token'
    required: true

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v5
      with:
        fetch-depth: 0  # Full history for setuptools-scm

    - uses: ./.github/actions/setup-python
      with:
        python-version: '3.11'
        requirements: '.[build]'

    - name: Debug - Before version override
      shell: bash
      run: |
        echo "Version override input: ${{ inputs.version-override }}"
        echo "SETUPTOOLS_SCM_PRETEND_VERSION before: ${SETUPTOOLS_SCM_PRETEND_VERSION:-NOT SET}"

    - name: Configure version for dev builds
      if: inputs.version-override != ''
      shell: bash
      run: |
        echo "Setting version override: ${{ inputs.version-override }}"
        echo "SETUPTOOLS_SCM_PRETEND_VERSION=${{ inputs.version-override }}" >> $GITHUB_ENV

    - name: Debug - After version override
      shell: bash
      run: |
        echo "SETUPTOOLS_SCM_PRETEND_VERSION after: ${SETUPTOOLS_SCM_PRETEND_VERSION:-NOT SET}"
        echo "All environment variables:"
        env | grep -i version || echo "No version-related env vars"

    - name: Debug - Check setuptools-scm version detection
      shell: bash
      run: |
        python -c "
        try:
            from setuptools_scm import get_version
            version = get_version()
            print(f'setuptools-scm detected version: {version}')
        except Exception as e:
            print(f'Error getting version: {e}')
        "

    - name: Build package
      shell: bash
      run: python -m build

    - name: Verify package
      shell: bash
      run: twine check dist/*

    - name: Upload to PyPI
      shell: bash
      run: |
        twine upload --repository-url ${{ inputs.pypi-upload-url }} dist/* --verbose
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ inputs.pypi-token }}

    - name: Verify installation
      shell: bash
      run: |
        PACKAGE_NAME=$(python -c "import tomli; print(tomli.load(open('pyproject.toml', 'rb'))['project']['name'])")
        pip install --index-url "${{ inputs.pypi-install-url }}" "$PACKAGE_NAME"
