name: 'Python Setup'
description: 'Setup Python and install dependencies'
inputs:
  python-version:
    description: 'Python version'
    required: false
    default: '3.11'

defaults:
  run:
    shell: bash

runs:
  using: 'composite'
  steps:
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ inputs.python-version }}

    - name: Upgrade pip
      run: python -m pip install --upgrade pip

    - name: Install dependencies
      run: pip install -r requirements-dev.txt
